title: Blog di Andrea Luzzi
author: Andrea Luzzi
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Questo blog Ã¨ stato fatto per il corso di introduzione a github.
  studente
  github
  jekyll
  aggiungere un tema

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
